### ISSUE TITLE
Improve Command Line Arguments

### ISSUE THREAD

**Issue by keeganryan** [AGFeldman/jaka#19]
Add the ability to specify test cases via the command line. Perhaps using the argparse module? This could also include a flag for generating the DOT output.

**Comment by AGFeldman** [comment]
Are you imagining specifying test cases by number instead of by file? IMO, this isn't a worthwhile use of time.

DOT output could be generated by a different script, there's no reason to do it from `run.py`. It would be nice if pdfs are automatically generated when we run `cases/generate.sh`.

**Comment by keeganryan** [comment]
I was thinking it could be useful to be able to specify

python run.py cases/case0.json --simulate
python run.py cases/case1.json --DOT
python run.py cases/case0.json --showStatistics stat1 stat2 stat3

I feel this makes more sense than passing in JSON through stdin, since it gives us more flexibility if we want to accept other command line input in the future. The question of whether it's worth our time is fair.

It would be fairly easy to add that capability to generate.sh

**Comment by AGFeldman** [comment]
Discussed offline, I think the plan is to have another python script that is called by `generate.sh`, and postpone other argument processing (like stat1 stat2 stat3) until we need it.

**Comment by AGFeldman** [comment]
Closing, we can re-open if/when we determine it's necessary
